### ISSUE TITLE
Notes so far

### ISSUE THREAD

**Issue by mrybak834** [null93/minesweeper#2]
**For the timer**
int gameStart = 0 when game is not in progress, 1 when game is in progress

**For bomb counter**
int bombsLeft = (Total Bombs - number of flags on the field)

**TBA**
Score counting - have to read up on what I need to report because I think there are deductions if the user detonated the bomb, mis-flagged a bomb, didn’t flag a bomb, etc.

If anything I’ll tally up the score in an
int userScore

**Notes on Board**
Must be un-resizable, way too much work with images

I made a button 26x26, and the board size 280x380. If you modify the board size, try to keep it in multiples of 10, and let me know, or modify the board how you want and i'll modify buttons to fit.

Grid must be : Jpanel x = new Grid();

**Comment by null93** [comment]
I pulled your changes and I changed the icon size for each coordinate to be 16 x 16 (original).  I will push Grid.java to reflect that change.
